---
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  # decrypt GCP credential file here
  - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in service_account.json.enc -out service_account.json -d

  # download GCP SDK and source it on travis instance
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # configure k8s and gcp interface
  - gcloud config set disable_prompts true
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file=service_account.json
  - gcloud config set project octocat-k8s
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials multi-cluster

  # login docker and build test react image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker build -t binhrobles binhrobles/react-test -f ./client/Dockerfile.dev

script:
  #- docker run -e CI=true binhrobles/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
