---
sudo: required
services:
  - docker

before_install:
  # decrypt GCP credential file here
  - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in service_account.json.enc -out service_account.json -d

  # download GCP SDK and source it on travis instance
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # configure k8s and gcp interface
  - gcloud components update kubectl
  - gcloud auth active-service-account --key-file service-account.json
